name: Extrair DODF Diariamente

on:
  schedule:
    - cron: '0 15 * * *'  # 12:00 UTC (9:00 BRT)
  workflow_dispatch:

jobs:
  run-extractor:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Instalar dependências
        run: |
          pip install PyPDF2 gspread google-auth urllib3
          
      - name: Configurar credenciais
        env:
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}  # Secret do GitHub
        run: |
          # Cria o arquivo 'projetodedadosjson' na raiz (SEM extensão .json)
          echo "$GOOGLE_CREDS_JSON" > projetodedadosjson
          # Debug: verifica estrutura de arquivos
          ls -la
          
      - name: Executar extrator
        run: |
          python app/ExtratorDados.py || echo "::error::Falha na execução"
