name: Extrair DODF Diariamente

on:
  schedule:
    - cron: '0 15 * * *'  # 12:00 UTC (9:00 BRT)
  workflow_dispatch:

jobs:
  run-extractor:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install PyPDF2 gspread google-auth urllib3
          
      - name: Executar extrator
        env:
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
        run: |
          # Lista arquivos para debug (opcional)
          ls -la
          # Executa o script
          python ExtratorDados.py || echo "::error::Falha ao executar script"
          # Mostra logs
          cat extrator.log || echo "Nenhum log encontrado"
