name: Extrair DODF Diariamente

on:
  schedule:
    - cron: '0 15 * * *'  # 9h BRT (12:00 UTC)
  workflow_dispatch:       # Permite rodar manualmente

jobs:
  run-extractor:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install PyPDF2 gspread google-auth urllib3
          
      - name: Executar extrator
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDS_JSON }}  # Corrigido para match com o código
        run: |
          cd app && python ExtratorDados.py
