name: Extrair DODF Diariamente

on:
  schedule:
    - cron: '0 15 * * *'  # 12:00 UTC (9:00 BRT)
  workflow_dispatch:

jobs:
  run-extractor:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install PyPDF2 gspread google-auth urllib3
          
      - name: Configurar credenciais
        env:
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
        run: |
          # Cria o arquivo JSON no caminho esperado pelo código (../projetodedadosjson)
          mkdir -p ../  # Garante que a pasta pai existe
          echo "$GOOGLE_CREDS_JSON" > ../projetodedadosjson
          # Debug: verifica se o arquivo foi criado
          ls -la ../
          
      - name: Executar extrator
        run: |
          # Executa o script (os logs agora aparecem apenas no terminal)
          python ExtratorDados.py || echo "::error::Falha ao executar script"
